open Compiler

(* [config.ml] is generated by test/e2e/dune from dune's %{workspace_root},
   giving an absolute path that's correct regardless of what cwd dune
   actually runs this test binary from -- avoids guessing at sandbox/build
   directory relative-path conventions entirely. *)
let runtime_dir = Filename.concat Config.workspace_root "runtime"
let fixtures_dir = Filename.concat Config.workspace_root "test/e2e/fixtures"

let read_file path =
  let ch = open_in path in
  let len = in_channel_length ch in
  let s = really_input_string ch len in
  close_in ch;
  s

let rm_rf dir =
  ignore (Sys.command (Printf.sprintf "rm -rf %s" (Filename.quote dir)))

(* Compiles a fixture through the real Driver (the same one bin/main.ml
   uses), links it with gcc against the real runtime, runs the resulting
   binary, and asserts its stdout matches the fixture's .expected file. This
   is the only layer that proves the compiler produces correct *running*
   programs, not just a correctly-shaped IR. *)
let run_fixture name =
  Alcotest.test_case name `Quick (fun () ->
      let source = read_file (Filename.concat fixtures_dir (name ^ ".oj")) in
      let expected =
        String.trim
          (read_file (Filename.concat fixtures_dir (name ^ ".expected")))
      in
      let tmp = Filename.temp_dir "compiler_e2e_" "" in
      Fun.protect
        ~finally:(fun () -> rm_rf tmp)
        (fun () ->
          let entry = Driver.compile_to_c ~filename:(name ^ ".oj") ~source in
          let c_file = Filename.concat tmp "generated.c" in
          Driver.emit_c_file ~out_path:c_file ~entry_body:entry;
          let out_exe = Filename.concat tmp "prog" in
          match Driver.build_exe ~c_file ~runtime_dir ~out_exe with
          | Error msg -> Alcotest.fail msg
          | Ok () ->
              let out_file = Filename.concat tmp "stdout.txt" in
              let cmd =
                Printf.sprintf "%s > %s" (Filename.quote out_exe)
                  (Filename.quote out_file)
              in
              let code = Sys.command cmd in
              Alcotest.(check int) (name ^ ": exit code") 0 code;
              let actual = String.trim (read_file out_file) in
              Alcotest.(check string) (name ^ ": stdout") expected actual))

let suite =
  List.map run_fixture
    [
      "arithmetic_let";
      "defrec_recursion";
      "if_branch";
      "list_pattern_match";
      "sum_type_pack_unpack";
    ]

let () = Alcotest.run "compiler e2e" [ ("e2e", suite) ]
